{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMpf1i4/ew3GcAT0Lybmq1i"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "VlHrIVhaUeS2",
        "outputId": "4f5abfbc-bbf7-4480-c078-8d28afc01096"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: streamlit in /usr/local/lib/python3.10/dist-packages (1.31.0)\n",
            "Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)\n",
            "Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n",
            "Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)\n",
            "Requirement already satisfied: importlib-metadata<8,>=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (7.0.1)\n",
            "Requirement already satisfied: numpy<2,>=1.19.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.23.5)\n",
            "Requirement already satisfied: packaging<24,>=16.8 in /usr/local/lib/python3.10/dist-packages (from streamlit) (23.2)\n",
            "Requirement already satisfied: pandas<3,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.5.3)\n",
            "Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)\n",
            "Requirement already satisfied: protobuf<5,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (10.0.1)\n",
            "Requirement already satisfied: python-dateutil<3,>=2.7.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.8.2)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)\n",
            "Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.7.0)\n",
            "Requirement already satisfied: tenacity<9,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.3)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.9.0)\n",
            "Requirement already satisfied: tzlocal<6,>=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.2)\n",
            "Requirement already satisfied: validators<1,>=0.2 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.22.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.41)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.8.1b0)\n",
            "Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.2)\n",
            "Requirement already satisfied: watchdog>=2.1.5 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.0.0)\n",
            "Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.3)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
            "Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)\n",
            "Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<8,>=1.4->streamlit) (3.17.0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.3.0->streamlit) (2023.4)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3,>=2.7.3->streamlit) (1.16.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.6)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.2.2)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.2.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.33.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.17.1)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "tTZsmuy1UhIw",
        "outputId": "ebaa1eed-3e2d-448c-c4bf-d37cc9164ed8"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "os.chdir(\"/content/drive/MyDrive\")"
      ],
      "metadata": {
        "id": "E5PGRMFCUhFK"
      },
      "execution_count": 13,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "with open(\"./app.py\", \"w\") as f:\n",
        "  f.write(\"\")"
      ],
      "metadata": {
        "id": "wjMQRx82U1dZ"
      },
      "execution_count": 14,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import files\n",
        "files.view(\"app.py\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 17
        },
        "id": "wLMTn3CCU_bM",
        "outputId": "de486e03-e914-4501-cb66-d54da0e0181c"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "\n",
              "      ((filepath) => {{\n",
              "        if (!google.colab.kernel.accessAllowed) {{\n",
              "          return;\n",
              "        }}\n",
              "        google.colab.files.view(filepath);\n",
              "      }})(\"/content/drive/MyDrive/app.py\")"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!streamlit run app.py & sleep 3 && npx localtunnel --port 8501"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "uvV9Yb1IVByz",
        "outputId": "bf385607-1837-48d3-fac5-0d1bf38d8616"
      },
      "execution_count": 15,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.\n",
            "\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n",
            "\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://23.236.55.226:8501\u001b[0m\n",
            "\u001b[0m\n",
            "\u001b[K\u001b[?25hnpx: installed 22 in 2.183s\n",
            "your url is: https://all-plants-smile.loca.lt\n",
            "北海道の現在の天気:\n",
            "気温: -0.8999999761581421℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "青森の現在の天気:\n",
            "気温: 1.25℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "岩手の現在の天気:\n",
            "気温: 3.3499999046325684℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "宮城の現在の天気:\n",
            "気温: 6.449999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "秋田の現在の天気:\n",
            "気温: 3.1500000953674316℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "山形の現在の天気:\n",
            "気温: 3.3499999046325684℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "福島の現在の天気:\n",
            "気温: 5.849999904632568℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "茨城の現在の天気:\n",
            "気温: 8.800000190734863℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "栃木の現在の天気:\n",
            "気温: 9.100000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "群馬の現在の天気:\n",
            "気温: 9.699999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "埼玉の現在の天気:\n",
            "気温: 9.449999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "千葉の現在の天気:\n",
            "気温: 8.899999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "東京の現在の天気:\n",
            "気温: 9.800000190734863℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "神奈川の現在の天気:\n",
            "気温: 8.800000190734863℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "新潟の現在の天気:\n",
            "気温: 5.699999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "富山の現在の天気:\n",
            "気温: 6.599999904632568℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "石川の現在の天気:\n",
            "気温: 7.099999904632568℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "福井の現在の天気:\n",
            "気温: 7.650000095367432℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "山梨の現在の天気:\n",
            "気温: 8.600000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "長野の現在の天気:\n",
            "気温: 3.3499999046325684℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "岐阜の現在の天気:\n",
            "気温: 11.149999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "静岡の現在の天気:\n",
            "気温: 10.949999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "愛知の現在の天気:\n",
            "気温: 11.0℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "三重の現在の天気:\n",
            "気温: 10.600000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "滋賀の現在の天気:\n",
            "気温: 8.5℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "京都の現在の天気:\n",
            "気温: 9.25℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "大阪の現在の天気:\n",
            "気温: 9.75℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "兵庫の現在の天気:\n",
            "気温: 7.949999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "奈良の現在の天気:\n",
            "気温: 9.5℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "和歌山の現在の天気:\n",
            "気温: 8.649999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "鳥取の現在の天気:\n",
            "気温: 7.25℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "島根の現在の天気:\n",
            "気温: 8.149999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "岡山の現在の天気:\n",
            "気温: 9.949999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "広島の現在の天気:\n",
            "気温: 9.399999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "山口の現在の天気:\n",
            "気温: 9.100000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "徳島の現在の天気:\n",
            "気温: 8.699999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "香川の現在の天気:\n",
            "気温: 8.350000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "愛媛の現在の天気:\n",
            "気温: 9.050000190734863℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "高知の現在の天気:\n",
            "気温: 10.149999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "福岡の現在の天気:\n",
            "気温: 10.5℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "佐賀の現在の天気:\n",
            "気温: 10.399999618530273℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "長崎の現在の天気:\n",
            "気温: 9.100000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "熊本の現在の天気:\n",
            "気温: 10.850000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "大分の現在の天気:\n",
            "気温: 8.949999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "宮崎の現在の天気:\n",
            "気温: 12.850000381469727℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "鹿児島の現在の天気:\n",
            "気温: 12.449999809265137℃\n",
            "降水量: 0.0mm\n",
            "\n",
            "沖縄の現在の天気:\n",
            "気温: 15.449999809265137℃\n",
            "降水量: 0.20000000298023224mm\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 20516 (\\N{CJK UNIFIED IDEOGRAPH-5024}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 21271 (\\N{CJK UNIFIED IDEOGRAPH-5317}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 28023 (\\N{CJK UNIFIED IDEOGRAPH-6D77}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 36947 (\\N{CJK UNIFIED IDEOGRAPH-9053}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 12398 (\\N{HIRAGANA LETTER NO}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 27671 (\\N{CJK UNIFIED IDEOGRAPH-6C17}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 28201 (\\N{CJK UNIFIED IDEOGRAPH-6E29}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 12392 (\\N{HIRAGANA LETTER TO}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 38477 (\\N{CJK UNIFIED IDEOGRAPH-964D}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 27700 (\\N{CJK UNIFIED IDEOGRAPH-6C34}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 37327 (\\N{CJK UNIFIED IDEOGRAPH-91CF}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 25512 (\\N{CJK UNIFIED IDEOGRAPH-63A8}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 31227 (\\N{CJK UNIFIED IDEOGRAPH-79FB}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 26178 (\\N{CJK UNIFIED IDEOGRAPH-6642}) missing from current font.\n",
            "\n",
            "/usr/local/lib/python3.10/dist-packages/streamlit/elements/pyplot.py:161: UserWarning:\n",
            "\n",
            "Glyph 38291 (\\N{CJK UNIFIED IDEOGRAPH-9593}) missing from current font.\n",
            "\n",
            "2024-02-09 06:37:36.320 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 165, in <module>\n",
            "    main()\n",
            "  File \"/content/drive/MyDrive/app.py\", line 130, in main\n",
            "    current_temperature_2m, current_precipitation, current_weather_jp, hourly_data = get_weather(latitude, longitude)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 84, in get_weather\n",
            "    responses = openmeteo.weather_api(url, params=params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 47, in weather_api\n",
            "    return self._get(WeatherApiResponse, url, params, method)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 30, in _get\n",
            "    raise OpenMeteoRequestsError(response_body)\n",
            "openmeteo_requests.Client.OpenMeteoRequestsError: {'error': True, 'reason': 'Forecast days is invalid. Allowed range 0 to 16. Given 16.'}\n",
            "2024-02-09 06:37:38.050 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 165, in <module>\n",
            "    main()\n",
            "  File \"/content/drive/MyDrive/app.py\", line 130, in main\n",
            "    current_temperature_2m, current_precipitation, current_weather_jp, hourly_data = get_weather(latitude, longitude)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 84, in get_weather\n",
            "    responses = openmeteo.weather_api(url, params=params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 47, in weather_api\n",
            "    return self._get(WeatherApiResponse, url, params, method)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 30, in _get\n",
            "    raise OpenMeteoRequestsError(response_body)\n",
            "openmeteo_requests.Client.OpenMeteoRequestsError: {'error': True, 'reason': 'Forecast days is invalid. Allowed range 0 to 16. Given 16.'}\n",
            "2024-02-09 06:40:22.211 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 174, in <module>\n",
            "    main()\n",
            "  File \"/content/drive/MyDrive/app.py\", line 142, in main\n",
            "    current_temperature_2m, current_precipitation, current_weather_jp, hourly_data = get_weather(latitude, longitude)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 96, in get_weather\n",
            "    responses = openmeteo.weather_api(url, params=params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 47, in weather_api\n",
            "    return self._get(WeatherApiResponse, url, params, method)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 30, in _get\n",
            "    raise OpenMeteoRequestsError(response_body)\n",
            "openmeteo_requests.Client.OpenMeteoRequestsError: {'error': True, 'reason': 'Forecast days is invalid. Allowed range 0 to 16. Given 16.'}\n",
            "2024-02-09 06:40:23.674 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 174, in <module>\n",
            "    main()\n",
            "  File \"/content/drive/MyDrive/app.py\", line 142, in main\n",
            "    current_temperature_2m, current_precipitation, current_weather_jp, hourly_data = get_weather(latitude, longitude)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 96, in get_weather\n",
            "    responses = openmeteo.weather_api(url, params=params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 47, in weather_api\n",
            "    return self._get(WeatherApiResponse, url, params, method)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 30, in _get\n",
            "    raise OpenMeteoRequestsError(response_body)\n",
            "openmeteo_requests.Client.OpenMeteoRequestsError: {'error': True, 'reason': 'Forecast days is invalid. Allowed range 0 to 16. Given 16.'}\n",
            "2024-02-09 06:40:59.604 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 174, in <module>\n",
            "    main()\n",
            "  File \"/content/drive/MyDrive/app.py\", line 142, in main\n",
            "    current_temperature_2m, current_precipitation, current_weather_jp, hourly_data = get_weather(latitude, longitude)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 96, in get_weather\n",
            "    responses = openmeteo.weather_api(url, params=params)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 47, in weather_api\n",
            "    return self._get(WeatherApiResponse, url, params, method)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/openmeteo_requests/Client.py\", line 30, in _get\n",
            "    raise OpenMeteoRequestsError(response_body)\n",
            "openmeteo_requests.Client.OpenMeteoRequestsError: {'reason': 'Past days is invalid. Allowed range 0 to 92. Given 96.', 'error': True}\n",
            "2024-02-09 06:47:12.307 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 175, in <module>\n",
            "    main()\n",
            "  File \"/content/drive/MyDrive/app.py\", line 132, in main\n",
            "    selected_locations = st.multiselect(\"地域を選択\", list(locations.keys()))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/metrics_util.py\", line 397, in wrapped_func\n",
            "    result = non_optional_func(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/multiselect.py\", line 258, in multiselect\n",
            "    return self._multiselect(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/elements/widgets/multiselect.py\", line 337, in _multiselect\n",
            "    widget_state = register_widget(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 161, in register_widget\n",
            "    return register_widget_from_metadata(metadata, ctx, widget_func_name, element_type)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/state/widgets.py\", line 206, in register_widget_from_metadata\n",
            "    raise DuplicateWidgetID(\n",
            "streamlit.errors.DuplicateWidgetID: There are multiple identical `st.multiselect` widgets with the\n",
            "same generated key.\n",
            "\n",
            "When a widget is created, it's assigned an internal key based on\n",
            "its structure. Multiple widgets with an identical structure will\n",
            "result in the same internal key, which causes this error.\n",
            "\n",
            "To fix this error, please pass a unique `key` argument to\n",
            "`st.multiselect`.\n",
            "2024-02-09 06:47:36.456 Uncaught app exception\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py\", line 535, in _run_script\n",
            "    exec(code, module.__dict__)\n",
            "  File \"/content/drive/MyDrive/app.py\", line 129, in <module>\n",
            "    main()\n",
            "NameError: name 'main' is not defined. Did you mean: 'min'?\n",
            "\u001b[34m  Stopping...\u001b[0m\n",
            "^C\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "CX5X236_UCw5"
      },
      "execution_count": 14,
      "outputs": []
    }
  ]
}